### ISSUE TITLE
GWT 2.7 RC1 : java.lang.ClassNotFoundException: com$gwtplatform$dispatch$rest$client$RestGinModule

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#614] opened 2014-11-01 19:49 UTC
When I use GWT 2.7RC1 and include:

```
<inherits name='com.gwtplatform.dispatch.rest.DispatchRest'/>
```
I did what was on this page (https://github.com/ArcBees/GWTP/wiki/Rest-Dispatch#add-rest-dispatch-to-your-gwtxml) in the important note.

I get the following error will running SuperDevMode and incremental compile:

```
GET /recompile/mobilePhoneGapIOS
   Job test.mobile.MobilePhoneGapIOS_1_18
      starting job: test.mobile.MobilePhoneGapIOS_1_18
      binding: mgwt.density=xhigh
      Compiling module test.mobile.MobilePhoneGapIOS
         Computing all possible rebind results for 'com.googlecode.gwtphonegap.client.log.shared.PhoneGapLogService'
            Rebinding com.googlecode.gwtphonegap.client.log.shared.PhoneGapLogService
               Invoking generator com.googlecode.gwtphonegap.rebind.PhoneGapServiceInterfaceProxyGenerator
                  Generating client proxy for remote service interface 'com.googlecode.gwtphonegap.client.log.shared.PhoneGapLogService'
                     Analyzing 'com.googlecode.gwtphonegap.client.log.shared.PhoneGapLogService' for serializable types
                        Analyzing methods:
                           public abstract java.lang.String logOnServer(java.lang.String clientId, java.util.List<java.util.logging.LogRecord> record)
                              Parameter: java.util.List<java.util.logging.LogRecord> record
                                 java.util.List<java.util.logging.LogRecord>
                                    Verifying instantiability
                                       com.google.common.collect.SingletonImmutableList<java.util.logging.LogRecord>
                                          Checking parameters of 'com.google.common.collect.SingletonImmutableList<java.util.logging.LogRecord>'
                                             Checking type argument 0 of type 'com.google.common.collect.SingletonImmutableList<E>' because it is directly exposed in this type or in one of its subtypes
                                                java.util.logging.LogRecord
                                                   Verifying instantiability
                                                      java.util.logging.LogRecord
                                                         Analyzing the fields of type 'java.util.logging.LogRecord' that qualify for serialization
                                                            private java.lang.Throwable thrown
                                                               java.lang.Throwable
                                                                  Verifying instantiability
                                                                     com.gwtplatform.dispatch.client.interceptor.InterceptorMismatchException
                                                                        Analyzing the fields of type 'com.gwtplatform.dispatch.client.interceptor.InterceptorMismatchException' that qualify for serialization
                                                                           [WARN] Field 'private final java.lang.Class<?> requestedActionType' will not be serialized because it is final
                                                                           [WARN] Field 'private final java.lang.Class<?> supportedActionType' will not be serialized because it is final
         Computing all possible rebind results for 'com.gwtplatform.mvp.client.DesktopGinjector'
            Rebinding com.gwtplatform.mvp.client.DesktopGinjector
               Invoking generator com.google.gwt.inject.rebind.GinjectorGenerator
                  [ERROR] Unable to load gin module type [com.gwtplatform.dispatch.rest.client.RestGinModule], maybe you haven't compiled your client java sources?
java.lang.ClassNotFoundException: com$gwtplatform$dispatch$rest$client$RestGinModule
	at com.google.gwt.inject.rebind.GinBridgeClassLoader.findClass(GinBridgeClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.google.gwt.inject.rebind.GinBridgeClassLoader.loadClass(GinBridgeClassLoader.java:108)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at com.google.gwt.inject.rebind.GinjectorGenerator.loadClass(GinjectorGenerator.java:223)
	at com.google.gwt.inject.rebind.GinjectorGenerator.getPropertyModuleClasses(GinjectorGenerator.java:137)
	at com.google.gwt.inject.rebind.GinjectorGenerator.getModuleClasses(GinjectorGenerator.java:116)
	at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:72)
	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:760)
	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:160)
	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
	at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:87)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:485)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:443)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:576)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:306)
	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:248)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:67)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
	at com.google.gwt.dev.jjs.ast.JReturnStatement.traverse(JReturnStatement.java:40)
	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)
	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:351)
	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:145)
	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:600)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:569)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1505)
	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:870)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1303)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1036)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.precompile(JavaToJavaScriptCompiler.java:953)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.precompile(MonolithicJavaToJavaScriptCompiler.java:303)
	at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:38)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:286)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
	at com.google.gwt.dev.Compiler.run(Compiler.java:206)
	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:323)
	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:164)
	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:121)
	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:128)
	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:60)
	at com.google.gwt.dev.codeserver.JobRunner.access$100(JobRunner.java:31)
	at com.google.gwt.dev.codeserver.JobRunner$1.run(JobRunner.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
         [ERROR] Errors in 'gen/com/gwtplatform/mvp/client/DesktopGinjectorProvider.java'
            [ERROR] Line 8: Failed to resolve 'com.gwtplatform.mvp.client.DesktopGinjector' via deferred binding
         Unification traversed 7163 fields and methods and 1100 types. 518 are considered part of the current module and 518 had all of their fields and methods traversed.
      [ERROR] Compiler returned false
      [WARN] recompile failed
      [WARN] continuing to serve previous version

```

**Comment by BenDol** [comment] 2015-01-21 01:51
Still getting this issue since I use an entrypoint. I would love to change to the MvpWithEntryPoint, but my application loads in a particular way where the resources must come first. As far as I have tested this only works in my onModuleLoad call.

**Comment by meriouma** [comment] 2015-02-28 19:17
Still having the issue with GWTP-1.4?

**Comment by nmorel** [comment] 2015-03-02 13:37
Just tested on my project. I'm still having the issue with 1.4.

**Comment by christiangoudreau** [comment] 2015-03-02 13:39
@Chris-V

**Comment by Chris-V** [comment] 2015-03-02 13:48
Can't do anything here. If my workaround described previously doesn't work, we have to wait for the next release of GWT. That is given their fix works (makes the generation order of entry points deterministic again).

**Comment by christiangoudreau** [comment] 2015-03-02 14:09
Can anyone try with GWT trunk then? Since the fix will be included in GWT 2.8?

**Comment by nmorel** [comment] 2015-03-05 13:57
The last test I did was with a GWT 2.7.0 + fix from GWT team.

We replaced gwtp with an annotation processor (it has less features but enough for our need) so I can't test with GWT trunk right now.

Maybe @BenDol can test more easily or give a project that reproduce the problem ?
The hello-world project seems too simple to reproduce now.

**Comment by Chris-V** [comment] 2015-03-06 19:08
I'm gonna try implementing rebind rules to be used as a backup if the gin module is generated after the gin generator kicks in. That should solve the problem, but is still a decent amount and will potentially introduce some marker interfaces. I can't put an ETA on that for now.

**Comment by BenDol** [comment] 2015-03-07 04:24
@nmorel I can setup a project that reproduces the issue if needed, but I have applied MvpWithEntryPoint module rather than invoking my own EntryPoint. Let me know if it would help since I  can just fork an older version and allow access to the Arcbee's team.

**Closed** 2015-04-11 13:48 UTC

**Comment by alphathesis** [comment] 2016-08-23 01:34
Hi everyone!

I'm new to GWTP and Rest-Dispatch. I landed on this page because I'm also experiencing a similar issue when trying to use Rest-Dispatch. I've gathered that going the resource-delegates route is the best way to tie the client to the server. 

I'm therefore doing the following:

    ```
<!--Important: DispatchRest MUST come before MvpWithEntryPoint -->
    <!-- <inherits name="com.gwtplatform.dispatch.rest.DispatchRest"/> -->
    <inherits name="com.gwtplatform.dispatch.rest.delegates.ResourceDelegate"/>
    <inherits name='com.gwtplatform.mvp.MvpWithEntryPoint'/>
```

My pom includes just one maven dependency:

```
<dependency>
		    <groupId>com.gwtplatform.extensions</groupId>
		    <artifactId>dispatch-rest-delegates</artifactId>
		    <version>1.5.3</version>
		    <scope>provided</scope>
		</dependency>
```

Adding the other two dependencies identified here http://dev.arcbees.com/gwtp/communication/index.html#use-your-rest-resources is causing a ClassDefNotFound error on the EventBus. So my presumption is you only need one to add the delegate one.

But I'm still getting this error:

```
[ERROR] Errors in 'gen/com/gwtplatform/dispatch/rest/delegates/client/com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java'
            [ERROR] Line 17: Failed to resolve 'com.gwtplatform.dispatch.rest.delegates.client.ResourceDelegate' via deferred binding
         Computing all possible rebind results for 'com.rezi.client.application.main.tenant.gallary.GalleryView.Binder'
            Rebinding com.rezi.client.application.main.tenant.gallary.GalleryView.Binder
               Invoking generator com.google.gwt.uibinder.rebind.UiBinderGenerator
```

Can any one of you help me troubleshoot this issue please; I've spent numerous hours trying different options but now feel like I'm going in circles.

Thanks in advance.
